### ISSUE TITLE
Wireflow + Breakdown

### ISSUE THREAD

**Issue by Annevd** [DamianR2004/your-tribe-for-life-squad-page#14]

**Comment by Annevd** [comment]
Nadat wij als team een ontwerp hebben gekozen ben ik bezig geweest met een uitgebreide breakdown van het ontwerp. Hierin staat de tot nu toe benodigde HTML en basic CSS.

<img width=600 src="https://github.com/user-attachments/assets/aa6f5b3d-a9b0-4515-989e-f2a749035b4f">

**Comment by DamianR2004** [comment]
![IMG_0006](https://github.com/user-attachments/assets/d3ac63af-81d4-4e38-bd5c-840c84f26686)


[Naamloos 29.pdf](https://github.com/user-attachments/files/16887963/Naamloos.29.pdf)


Hier heb ik ons wireflow toegevoegd. Hier is te zien waar de gebruiker heen kan mocht deze op bepaalde knoppen of links klikken. Ook zijn hier verschillende states te zien. In de beschrijving staat wat uitgebreider hoe de website gaat werken.
