### ISSUE TITLE
1 <ul> met meerdere <li> ipv andersom

### ISSUE THREAD

**Issue by rutgerkock** [DamianR2004/your-tribe-for-life-squad-page#19]
https://github.com/DamianR2004/your-tribe-for-life-squad-page/blob/f18afdbb62521403402b65c587f331d275967bdc/src/routes/%2Bpage.svelte#L5-L13

Jullie hebben momenteel voor elke persoon een losse lijst, dit lijkt niet de bedoeling te zijn voor hoe het er nu uit ziet. Zet je 
`ul` boven de `#each` zodat je alleen losse `<li>` aangemaakt per persoon.
![image](https://github.com/user-attachments/assets/3bdc2f54-2d5b-4009-8bdc-5c61be0a181b)

**Comment by DamianR2004** [comment]
Is gefixt, danku😁


<img width="500" alt="Scherm­afbeelding 2024-09-16 om 11 38 09" src="https://github.com/user-attachments/assets/7a68b6f8-9407-4b6f-aa99-aa1e308af577">
