### ISSUE TITLE
Squadpage ontwerpen

### ISSUE THREAD

**Issue by Annevd** [DamianR2004/your-tribe-for-life-squad-page#2]
Je kunt het ontwerp maken als teamlid, met meerdere teamleden of met het hele team. Je kunt daarbij delen van het ontwerp uitwerken of het gehele ontwerp in een keer aanpakken. Ongeacht welke methode je kiest is het belangrijk meerdere iteraties te maken. Bespreek (delen van) het ontwerp en haal daarbij breed (teamleden, peers en docenten) feedback op in de vorm van issues in GitHub.

NB: Het is fijn als je screenshots van versies van het ontwerp opneemt in de issue-thread zodat de ontstaansgeschiedenis van het definitieve ontwerp navolgbaar wordt. Neem ook links of screenshots van inspiratiebronnen op.

- Werk gemaakte afspraken uit in een ontwerp
- Bespreek het ontwerp met het team
- Noteer opmerkingen
- Itereer (begin weer bij stap 1)
- — na een aantal iteraties —
- Breek het ontwerp op in kleine behapbare delen en maak daar issues voor aan in het projectboard

**Comment by Annevd** [comment]
## Ontwerp Mondriaan
Als overduidelijke inspiratie heb ik de schilderijen van Piet Mondriaan gebruikt. Hiervan zullen de 3 primaire kleuren rood, blauw en geel vaak terugkomen.

**Voorbeeld inspiratie:**

<img  width=250 height=250 src="https://github.com/user-attachments/assets/e375c5c9-914b-4c86-a6c7-212acc9ae3af">

### Het ontwerp:

![Image](https://github.com/user-attachments/assets/aea6b949-3237-48fd-a777-448586c553a8)

Het idee is dat alle visitekaartjes zich in de vlakken van het schilderij bevinden. Ook is er de mogelijkheid om te filteren op de verschillende squads of op ons team. Tot slot kan je op een vlak klikken om het visitekaartje van je klasgenoten beter te bekijken.

**Comment by DamianR2004** [comment]
[Naamloos 27.pdf](https://github.com/user-attachments/files/16848506/Naamloos.27.pdf)

Voor deze opdracht hebben we de taak gekregen om een squadpage te maken door middel van svelteKit. Hiervoor is er ook weer een ontwerp gemaakt. Het idee dat we hadden is om een Mondriaan te maken waar kaartjes van alle squadleden in komen te staan. Dit idee is uit te werken door gebruik te maken van een grid, met een area template. Door middel van een filter willen we op Squad en ons eigen team filteren.

Voor de kaartjes wil ik een loop maken zodat er voor elk lid unieke data voor de kaartjes zijn. Dit betreft een naam en een image. Ook moet het nog mogelijk zijn dat elk kaartje een aparte link krijgt. Tenslotte willen we ook nog de description laten zien, dit moet kunnen met een JS overlay.

**Comment by amirnapoletano** [comment]
Eerste schets van de Home pagina met hero section 

![image](https://github.com/user-attachments/assets/650c2979-ded4-42c3-9273-854d473de082)

**Comment by Einanas** [comment]
Dit zijn mijn schetsen. Het eerste is heeft slides met foto's van iedereen, de tweede met de "class page" laat zien wie bij welke klas hoort en vouwt de kaarten uit. De derde met "People" kan je sliden door de personen/foto's heen en kan je zien wat hun naam en bijv. socials zijn.
Ik ben momenteel bezig met een Figma tekening zodat je kan zien hoe het er werkelijk uit ziet. Ik heb het vanavond hierin staan.
![IMG_20240903_170851_hdr~2](https://github.com/user-attachments/assets/e48d3d5d-66ff-4237-9e89-32f63a0c53f8)
![IMG_20240903_170913_hdr~2](https://github.com/user-attachments/assets/1a60c608-518d-44b3-a128-57d0ff790973)

**Comment by Remy2072** [comment]
Maandag hadden wij gezamenlijk als team afgesproken dat iedereen een schets gaat maken voor de squadpage. Ik ben gelijk begonnen met een hi-fi schets in Figma. De bedoeling van deze user story is dat we vier verschillende squadpages hebben, waar we er één van kiezen als basis en daarop verder werken. Ik heb voor een donkere stijl gekozen die een goed contrast geeft op de vlakken.

![Image](https://github.com/user-attachments/assets/7292f261-bd78-4028-8142-697814e2db7d)

**Comment by Einanas** [comment]
Eind beslissing is de ⭐Mondriaan⭐ design.

**Comment by DamianR2004** [comment]
Checkkkk

**Comment by Annevd** [comment]
## 9-9 Opdracht squadpage ontwerpen

- Maak je ontwerp na in Figma als je alleen nog een schets op papier hebt. Pas de Figma oefeningen toe die je hebt geleerd. Gebruik 'Text styles' en 'color styling' voor het consitent gebruik van stylen. Gebruik componenten voor elementen die vaker terugkomen. 

- Voordat je gaat varieren en experimenteren met de layout van de overzichtpagina gaan jullie eerst inspiratie zoeken. Verzamel dit in jullie gezamenlijke Figma file.

- Ga daarna verschillende ontwerpen maken met je team, dupliceer een artboard elke keer als je een nieuwe variatie gaat maken:

-  **Hiërarchie bepalen** Pak je (laatste) ontwerp en vraag jezelf eens af: “Wat moeten mensen als eerste zien?” Omcirkel de belangrijkste informatie, belangrijke details en achtergrondinformatie.

-  **Variaties maken** Maak minimaal 4 verschillende versies van het ontwerp in Figma, waarin je visuele hiêrarchie aanbrengt door middle van grootte, positie op het scherm, witruimte en kleur/contrast.

-  **Feedback** Bespreek alle variaties in je team. Leg bij elke schets uit hoe je visuele hiërarchie hebt toegepast.

- Maak een **nieuw ontwerp** voor de squadpage in Figma waarin jullie de nieuwe ideeeën en feedback verwerken

## Uitwerking

Vorige week hadden we als team al de keuze gemaakt om een mondriaan schilderij te gaan maken met in alle vlakken de visitekaartjes.

In het figma bestand hebben wij als eerst al onze inspiratie in een aparte pagina gezet. Om dit netjes uit te lijnen hebben we de grid layout functie van Figma gebruikt.

Omdat een Mondriaan wel gewoon een Mondriaan moet blijven, hebben wij besloten geen variaties te maken, maar ons te focussen op het uiteindelijk uitgewerkte Figma design van ons idee. 

Qua visuele hiërarchie springen de letters van de squads en "ons team" er wel uit met sierlijke letters en een grote lettergrootte. De sierlijke letters zullen een interessant contrast bieden tegenover de strakke lijnen van een Mondriaan.

**[Dit](https://www.figma.com/design/KgldIUCaU6y5VhAcdIgxnn/Squadpage-Sprint-13?node-id=80-18&node-type=CANVAS&t=AGCTYgMBoLA87B8R-0) is het uitgewerkte design geworden voor mobiel en desktop:**

![Image](https://github.com/user-attachments/assets/93cb9eb1-fa7a-4b00-ae98-6b9a36e13b9a)
