### ISSUE TITLE
Custom properties voor kleuren

### ISSUE THREAD

**Issue by Annevd** [DamianR2004/your-tribe-for-life-squad-page#6]

**Comment by DamianR2004** [comment]
Verschillende custom properties zijn toegevoegd voor de kleuren, nu worden de 'officiele' mondriaan kleuren ook echt gebruikt.

https://github.com/DamianR2004/your-tribe-for-life-squad-page/blob/8021985f5b7b6d411a722cdeecd652efc554a8b9/static/css/global.css#L10-L17

Dit is terug te vinden in verschillende grid areas.

https://github.com/DamianR2004/your-tribe-for-life-squad-page/blob/8021985f5b7b6d411a722cdeecd652efc554a8b9/src/routes/E/%2Bpage.svelte#L75-L79
