### ISSUE TITLE
Font kiezen en toepassen op  tekst

### ISSUE THREAD

**Issue by Annevd** [DamianR2004/your-tribe-for-life-squad-page#7]
## DLC: Analyseren & Ontwerpen

**Comment by Einanas** [comment]
Ik heb een aantal fonts gevonden bij Google fonts en heb het hieronder verdeeld in 3 secties. De eerste "Nope" was een beetje blok letters, soort letters die scherpe vormen heeft. 

Nope
https://fonts.google.com/specimen/Handjet
https://fonts.google.com/specimen/Space+Grotesk
https://fonts.google.com/specimen/Tomorrow

Na het bespreken met de rest van de team is de sectie "Nope" toch niet passend voor het design. Anne heeft ook haar mening gedeeld en wilde liever een 'Cursive / Handwritten' achtig font omdat het aansluit op _kunst_. Dus onder "Maybe" heb ik weer een aantal 'cursive / handwritten' suggesties gevonden. Ze zijn leuk maar toch niet helemaal precies wat ze wilde.

Maybe
https://fonts.google.com/specimen/Sacramento?classification=Handwriting
https://fonts.google.com/specimen/Allura?classification=Handwriting
https://fonts.google.com/specimen/Mrs+Sheppards?classification=Handwriting
https://fonts.google.com/specimen/Italianno?classification=Handwriting
https://fonts.google.com/specimen/Princess+Sofia?classification=Handwriting

Uiteindelijk ben ik verder gaan zoeken op een andere website. Ik heb de twee linkjes onder de sectie "ouuu" want het zijn best aparte en mooie fonts. Dat zou kunnen aan sluiten op het design.

✨ ouuu ✨  
https://www.fontspace.com/rocketto-font-f41361
https://www.fontspace.com/night-wind-sent-sample-font-f25585

De volgende stap is dat ik dus de twee linkjes ga implementeren, uittesten en dan vergelijken om te zien welke de eindbesluit zal worden.
