### ISSUE TITLE
Detail kaartje bouwen

### ISSUE THREAD

**Issue by Annevd** [DamianR2004/your-tribe-for-life-squad-page#8]
## DLC:  Bouwen

Met detail kaartje bedoelen we de uitgebreide versies van de visitekaartjes wanneer je op het kaartje klikt, met een naam , descriptie en avatar. Het zou handig zijn om hier een component van te maken.
Haal het Id uit directus.

Bijvoorbeeld squad id: [https://fdnd.directus.app/items/person/?filter={"squad_id":3}](https://fdnd.directus.app/items/person/?filter=%7B%22squad_id%22:3%7D)

**Comment by Einanas** [comment]
<img width="794" alt="image" src="https://github.com/user-attachments/assets/1d018bb6-bdbe-4456-a13a-479d46f2ed16">
Volgens de light house test is mijn website volledig accessible, ofwel toegankelijk, zowel als mobiel als desktop.


![image](https://github.com/user-attachments/assets/7a281f21-0b3d-40c6-842e-7c15e14fd8d0)
SEO, ofwel search engine optimization, geeft een 91% voor de resultaten. Het enige wat ontbreekt wat het een 100% kan geven is dat er een meta ontbreekt in de ``` <head> ``` van de  ```<html>.```


De Performance (72%) en de Best Practices (71%) hebben beide een matige scoren.
<img width="794" alt="image" src="https://github.com/user-attachments/assets/da9384a7-5266-4fd9-8a58-d81f271450b1">
![image](https://github.com/user-attachments/assets/03b8a115-e02f-4c21-9af5-8635dac460f0)

Voor de Performance zijn er al een aantal dingen die weggewerkt moeten worden. Al die dingen komen van andere files. Of het komt van svelte zelf.

De Best Practices geeft aan dat er cookies worden gebruikt voor de afbeeldingen. Het heeft te maken met waar de persoon die afbeelding vandaan heeft want de lighthouse geeft aan dat het van discord komt en daardoor cookies erbij betrekt.
Ook geeft het aan dat er geen correctie aspect ratio is voor de afbeeldingen. Dit kan gefixt worden door de afbeeldingen een correcte hoogte en breedte te geven.


![image](https://github.com/user-attachments/assets/85fded3c-a9a3-481f-a031-2a16911698ed)
De Best Practices is van 71% naar 75% doordat ik dit heb gedaan in de code bij css:|
.card-image img {
    object-fit: contain;
}

Contain houdt in dat het afbeelding zich aanpast zonder dat het bij snijdt, ofwel dat het aspect ratio zich niet aanpast.
